2.73.342

diff --git a/bashlib_y b/bashlib_y
--- a/bashlib_y
+++ b/bashlib_y
@@ -924,8 +924,11 @@ require(){
 					fi
 					dbv $to_load $ret
 				else
+					error "-r '$to_load', failed."
 					dbv `ls -la $to_load`
-					die "cannot require '$to_load'."
+					source "$to_load"
+					ret = $?
+					#die "cannot require '$to_load'."
 				fi
 				for f in `(echo -E "$funcs"; declare -F) | sort | uniq -u | awk '{print $3}'`; do
 					#dbv FUNC_SOURCE["$f"]="$to_load"
