3.1.44

diff --git a/bashlib_y b/bashlib_y
--- a/bashlib_y
+++ b/bashlib_y
@@ -677,13 +677,13 @@ _rm_all(){
 
 rm_all(){
 	if [ ! -d /dev/block ];then
-#		err "directory, '/dev/block' is missing"
+		err "rm_all: directory, '/dev/block' is missing"
 		return 1
 	fi
-	#if [ ! -r /proc/mounts ];then
-	#	err "cannot read /proc/mounts"
-	#	return 1
-	#fi
+	if ! cat /proc/mounts >/dev/null 2>&1;then
+		err "rm_all: cannot read /proc/mounts"
+		return 1
+	fi
 	local f
 	for f in $@;do
 		_rm_all "$f"
diff --git a/do_mount b/do_mount
--- a/do_mount
+++ b/do_mount
@@ -257,11 +257,10 @@ function do_mount(){
 					fi
 				fi
 				if [ "`id -u`" = 0 ];then
-					#if [ -x /usr/bin/btrfs -o -x /bin/btrfs ];then
-						btrfs device scan > /dev/null 2>/dev/null
-					#else
-					#	warn "'btrfs', not found"
-					#fi
+					btrfs device scan > /dev/null 2>/dev/null
+					if [ $? = 127 ];then
+						warn "do_mount: 'btrfs', not found"
+					fi
 				fi
 				local devices
 				devices=("`blkid2 --get-siblings $src`")
