2.65.130

diff --git a/bashlib_y b/bashlib_y
--- a/bashlib_y
+++ b/bashlib_y
@@ -402,32 +402,79 @@ dbv(){
 }
 
 
-rm_all(){
+_rm_all(){
 	dbv $@
 	local d
 	local dlen
-	if [ -d $1 -a ! -L $1 ];then
-		d=$(realpath $1)
-		if [ "$d" = "/" ];then
-			die "cannot use rm_all to '/'"
+	local ln
+	local blockDevs
+	local f
+	local l
+	if [ ! -d /dev/block ];then
+		die "directory /dev/block is missing"
+	fi
+	for f in /dev/block/*;do
+		l="`readlink f`"
+		if [ "${l:0:3}" = "../" ];then
+			blockDevs+=("${l#../}")
 		fi
-		dlen=${#d}
-		dlen=$((dlen + 1))
-		cat /proc/mounts|awk '{print $2}'| sed '1!G;h;$!d' |while read ln;do
-			dbv "${ln:0:$dlen}"
-			dbv "$d"
-			if [ "${ln:0:$dlen}" = "$d" ];then
-				if ! umount $ln;then
-					die "cannot unmount '$ln'"
+	done
+	d=$(realpath $1)
+	if [ "$d" = "/" ];then
+		die "cannot use rm_all to '/'"
+	fi
+	dlen=${#d}
+	dlen=$((dlen + 1))
+	if [ ! -r /proc/mounts ];then
+		die "cannot read /proc/mounts"
+	fi
+	cat /proc/mounts|awk '{print $2}'| sort -r |while read ln;do
+		dbv "${ln:0:$dlen}"
+		dbv "$d"
+		if [ "${ln:0:$dlen}" = "$d" ];then
+			dbv "umount $ln"
+			if ! umount $ln;then
+				die "cannot unmount '$ln'"
+			fi
+		fi
+	done
+	local lnLen1
+	local fsType
+	local b
+	local doRm
+	cat /proc/mounts|awk '{print $2 $1}'| sort -r |while read ln;do
+		lnLen1=$((${#ln} + 1))
+		if [ "${d:0:$lnLen1}" = "$ln/" -o "$d" = "$ln" ];then
+			fsType="`echo "$ln" | awk '{print $2}'`"
+			if [ "$fsType" = "overlay" ];then
+				doRm=1
+			else
+				if ["${fsType:0:5}" = "/dev/" ];then
+					for b in $bockDevs[@]; do
+						if [ "$b" = "${fsType#/dev/}" ];then
+							doRm=1
+							break
+						fi
+					done
 				fi
 			fi
-		done
-		rm --one-file-system -rf $d
-	else
-		rm $1
-	fi
+			if [ -n "$doRm" ];then
+				rm --one-file-system -rf "$d"
+			else
+				die "cannot delete '#d'"
+			fi
+			break
+		fi
+	done
 }
 
+
+rm_all(){
+	local f
+	for f in $@;do
+		_rm_all "$f"
+	done
+}
 
 declare -A LOCAL_FUNC_IDS
 declare -A LOCAL_FUNC_EACH
