2.65.74

diff --git a/bashlib_y b/bashlib_y
--- a/bashlib_y
+++ b/bashlib_y
@@ -12,7 +12,7 @@ normal="\033[m"
 __FILE__() {
 	local f="`readlink -f "${BASH_SOURCE[1]}"`"
 	if [[ "$f" =~ [^\./A-Za-z0-9_] ]]; then
-		echo -e "$error"Cannot use path name, '$f'"$normal". >&2
+		echo -e "$error"Cannot use path name, $f"$normal". >&2
 		echo -e "$info"Alphabitical/numeric characters and '/', '.', '⧵' are usable for path name when using bashlib_y"$normal" >&2
 		return
 	fi
@@ -40,7 +40,7 @@ __SOURCE_PATH__(){ # path of link if symbolic linked to __FILE__
 	local f="`realpath "${BASH_SOURCE[1]}"`"
 	if [[ "$f" =~ [^\./A-Za-z0-9_] ]]; then
 		echo -e "$error"Cannot use path name, '$f'"$normal". >&2
-		echo -e "$info"Alphabitical/numeric characters and '/', '.', '⧵' are usable for path name when using bashlib_y"$normal" >&2
+		echo -e "$info"bitical/numeric characters and '/', '.', '⧵' are usable for path name when using bashlib_y"$normal" >&2
 		return
 	fi
 	echo "$f"
