2.60.37

diff --git a/bashlib_y b/bashlib_y
--- a/bashlib_y
+++ b/bashlib_y
@@ -27,7 +27,9 @@ function split(){
 }
 
 
+
 initialize_support_lib(){
+
 	if [ -z "$SCRIPT_TMP_DIR" ];then
 		declare -A SSH_PARAM_LIST
 		local f="`__FILE_NAME__`"
@@ -55,6 +57,7 @@ initialize_support_lib(){
 		SOURCES_LOADED=()
 		return 0
 	else
+	
 		return 1
 	fi
 }
@@ -64,6 +67,7 @@ if initialize_support_lib; then
 
 declare -A LOCAL_FUNCS
 declare -A SCRIPT_FILES
+
 
 dbv(){
 	if [ -n "$DEBUG" ];then
@@ -92,6 +96,7 @@ dbv(){
 		fi
 	fi
 }
+
 
 rm_all(){
 	local d
@@ -126,6 +131,8 @@ chain_bak(){
 	local verbose
 	local dryrun
 	local theFirst
+	local force
+	local reverse
 
 	while (( "$#" )); do
 		if [ "${1:0:1}" = "-" ];then
@@ -145,6 +152,9 @@ chain_bak(){
 						;;
 					"--reverse")
 						reverse=1
+						;;
+					"--force")
+						force="-f"
 						;;
 					*)
 						die "not supported option '$1'"
@@ -170,6 +180,9 @@ chain_bak(){
 						"r")
 							reverse=1
 							;;
+						"f")
+							force="-f"
+						;;
 						*)
 							die "not supported option -'$o'"
 							;;
@@ -181,119 +194,289 @@ chain_bak(){
 		fi
 		shift
 	done
+	local targv
+	if [ -n "$reverse" ];then
+		for ((i = ${#argv[@]} - 1; i >= 0; i--)); do
+			a=${argv[$i]}
+			tragv+=($a)
+		done
+		argv=targv
+	fi
+	
 	if [ -n "$help" ];then
 		echo "usage: chain_bak [options] SOURCE DEST [ DEST2 DEST3 ... ]
   SOURCE                      : source file name
   DEST(s)                     : destination file name
   (options)
-     -d, --diff               : check difference between SOURCE and DEST
-     -x, --exchange, --cyclic : exchange name cyclically
-     -v, --verbose            : verbose output
-     -r, --reverse            : reverse all action
-     -?, --help               : show this help messages"
+     -d, --diff               : Check difference between SOURCE and DEST
+     -f, --force              : Remove file(s) with same content (sould be accompanied by '-d' option)
+     -x, --exchange, --cyclic : Exchange name cyclically
+     -v, --verbose            : Verbose output
+     -r, --reverse            : Reverse all action
+     -?, --help               : Show this help messages"
 		exit 0
 	fi
 	if [ -n "$DEBUG" ];then
 		verbose=1
-	
 	fi
+	if [ -n "$force" ];then
+		if [ -z "$diff" ];then
+			force=
+		fi
+	fi
+	
 	function _mv_it(){
-		/bin/mv $verbose "$1" "$2"
+		/bin/mv $verbose "$@"
 	}
-	function _chain_bak(){
-		local f="$1"
-		shift
-		if [ "$f" = "$1" ];then
-			info "first argumemnt and second argument is same"
+	function _check_identity(){
+		if [ "$1" = "$2" ];then
+			err "source argument '$1' and destination argument '$2' is same"
 			return 1
 		fi
-		if [ ! -e "$f" ];then
-			die "'$f' does not exist"
+		if [ -e "$2" ];then
+			local L1="`readlink -f "$1"`"
+			local L2="`readlink -f "$2"`"
+			if [ "$Lf" = "$L1" ];then
+				err "source argument '$1' and destination argument '$2' is an identical file, '$L1'"
+				return 1
+			else
+				if [ "`stat -c "%D:%d:%i" "$Lf"`" = "`stat -c "%D:%d:%i" "$L1"`" ];then
+					err "source argument '$1' and destination argument '$2' is identical file"
+					return 1
+				fi
+			fi
+			if [ -n "$diff" ];then
+				if [ -f "$1" -a -f "$2" ]; then
+					if diff "$1" "$2" >/dev/null; then
+						if [ ! -n "$force" ];then
+							err "No difference between '$1' '$2'. Stop operation."
+							info "You can use force option (-f) to overcome this limitation by deleting '$2'"
+							return 1
+						else
+							info "No difference between '$1' '$2'."
+							return 0
+						fi
+					fi
+				fi
+			fi
+		fi
+		return 0
+	}
+
+	function _chain_bak(){
+		local beyondCenter
+		local f
+		if [ "$1" = "-" ];then
+			beyondCenter=1
+			shift
+			f="$1"
 		else
-			if [ -e "$1" ];then
-				if [ -n "$diff" ];then
-					if diff "$f" "$1" >/dev/null; then
-						info "no difference between '$f' '$1'"
+			if [ "$2" = "-" ];then
+				beyondCenter=1
+				f="$1"
+				shift
+			else
+				f="$1" # first argument
+			fi
+		fi
+		shift
+		if [ ! -e "$f" ];then
+			err "'$f' does not exist"
+			return 1
+		else
+			if [ "$#" = 0 ];then # only one argument
+				local theme
+				local center
+				local startFile=$f
+				if [[ "$f" =~ ^(.*)\.(\d+)$ ]];then
+					theme=${BASH_REMATCH[1]}
+					center=BASH_REMATCH[2]
+				else
+					theme=$1
+					center=0
+				fi
+				_chain_bak_find_max $center
+				if [ -n "$beyondCenter" ];then
+					_chain_bak_find_min $center
+					if ! _chain_bak2 $min; then
+						return 1
+					fi
+				else
+					if ! _chain_bak2 $center; then
 						return 1
 					fi
 				fi
-				if [ -e "$2" ];then
-					_chain_bak "$@"
+			else
+				if [ -n "$beyondCenter" ];then
+					die "Argument error. '-' with over-two arguments."
+				fi
+				if ! _check_identity "$f" "$1"; then
+					return 1
+				fi
+				if [ -n "$2" ];then
+					if ! _chain_bak "$@"; then
+						return 1
+					fi
 				else
 					if [ -n "$cyclic" ];then
-						local noCycDiff
-						if [ -n "$diff" ];then
-							if diff "$theFirst" "$1" >/dev/null; then
-								info "no difference between '$theFirst' '$1'"
-								noCycDiff=1
-							fi
+						if ! _check_identity "$f" "$1"; then
+							return 1
 						fi
-						if [ -z "$noCycDiff" ];then
-							cyclicPreserved="$1.$RANDOM$RANDOM$RANDOM"
-							_mv_it "$1" "$cyclicPreserved"
+						cyclicPreserved="$1.$RANDOM$RANDOM$RANDOM"
+						if ! _mv_it "$1" "$cyclicPreserved"; then
+							return 1
 						fi
-					else
-						_chain_bak2 "$1" 1
 					fi
 				fi
+				if ! _mv_it $force "$f" "$1"; then
+					return 1
+				fi
 			fi
 		fi
-		_mv_it "$f" "$1"
-		_chain_bak2_reverse "$f"
+		return 0
 	}
+	
+	
 	function _chain_bak2(){
-		if [ -e "$1.$2" ];then
-			local num=$2
-			local nxt="$1.$(num + 1))"
-			if [ -e "$nxt" ];then
-				_chain_bak2 "$1" $((num + 1))
-			fi
-			_mv_it "$1.$2" "$nxt"
+		local num="$1"
+		local f0
+		local f1
+		local isMax
+		if [ "$num" = "$center" ];then
+			f0="$startFile"
+		else
+			f0="$theme.$num"
 		fi
-	}
-	function _chain_bak_reverse(){
-		f="$1"
-		shift
-		if [ "$f" = "$1" ];then
-			info "first argumemnt and second argument is same"
+		if [ "$((num + 1))" = "$center" ];then
+			f1="$startFile"
+		else
+			f1="$theme.$((num + 1))"
+		fi
+		if [ "$((num + 1))" = "$max" ];then
+			isMax=1
+		fi
+		if ! _check_identity "$f0" "$f1"; then
 			return 1
 		fi
-		if [ "$#" = 0 ];then
-			_chain_bak2_reverse "$f" 1
+		if [ -z "$isMax" ];then
+			if ! _chain_bak2 "$((num + 1))"; then
+				return 1
+			fi
+		fi
+		if ! _mv_it $force "$f0" "$f1"; then
+			return 1
+		fi
+	}
+
+	function _chain_bak_find_max(){
+		local n=$(($1 + 1))
+		local t
+		if [ $n = 0 ];then
+			t="$theme"
 		else
-			if [  -e "$1" ];then
-				if [ -e "$f" ];then
-					_chain_bak2 "$f"
-				fi
-				_mv_it "$1" "$f"
-				_chain_bak_reverse "$1" "$@"
+			t="$theme.$n"
+		fi
+		if [ ! -e "$t" ];then
+			max=$2
+		else
+			_chain_bak_find_max $n
+		fi
+	}
+
+	function _chain_bak_find_min(){
+		local n=$(($1 - 1))
+		local t
+		if [ $n = 0 ];then
+			t="$theme"
+		else
+			t="$theme.$n"
+		fi
+		if [ ! -e "$t" ];then
+			max=$2
+		else
+			_chain_bak_find_min $n
+		fi
+	}
+
+	function _chain_bak_reverse(){
+		local beyondCenter
+		if [ "$1" = "-" ];then
+			beyondCenter=1
+			shift
+		else
+			if [ "$2" = "-" ];then
+				beyondCenter=1
+			fi
+		fi
+		local theme
+		local center
+		if [[ "$1" =~ ^(.*)\.((-|)(\d+))$ ]];then
+			theme=${BASH_REMATCH[1]}
+			center=$((BASH_REMATCH[2] + 1))
+		else
+			theme=$1
+			center=0
+		fi
+		local max
+		local min
+		_chain_bak_find_max "$center"
+		if [ -n "$beyondCenter" ];then
+			_chain_bak_find_min "$center"
+		else
+			min=$center
+		fi
+		local startFile=$1
+		_chain_bak_reverse2 $max
+	}
+	
+	
+	function _chain_bak_reverse2(){
+		local num="$1"
+		local f0
+		local f1
+		local isMin
+		if [ "$((num - 1))" = "$center" ];then
+			f1="$startFile"
+		else
+			f1="$theme.$((num - 1))"
+		fi
+		if [ "$num" = "$center" ];then
+			f0="$startFile"
+		else
+			f0="$theme.$num"
+		fi
+		if [ "$((num - 1))" = "$min" ];then
+			isMin=1
+		fi
+		if ! _check_identity "$f0" "$f1"; then
+			return 1
+		fi
+		if [ -z "$isMin" ];then
+			if ! _chain_bak2_reverse2 "$((num - 1))"; then
+				return 1
+			fi
+		fi
+		if ! _mv_it $force "$f0" "$f1"; then
+			return 1
+		fi
+	}
+
+
+	if ((#argv >= 2));then
+		theFirst="${argv[0]}"
+		if _chain_bak "${argv[@]}"; then
+			if [ -n "$cyclicPreserved" ];then
+				_mv_it "$cyclicPreserved" "$theFirst"
 			else
-				die "'$1' does not exist"
+				_chain_bak_reverse "${argv[0]}"
 			fi
 		fi
-	}
-	function _chain_bak2_reverse(){
-		if [ "$#" = "1" ];then
-			if [ -e "$1.1" ];then
-				_mv_it "$1.1" "$1"
-				_chain_bak2_reverse "$1" 1
-			fi
-		else
-			local num=$2
-			local nxt="$1.$(num + 1))"
-			if [ -e "$nxt" ];then
-				_mv_it "$nxt" "$1.$2"
-				_chain_bak2_reverse "$1" $((num + 1))
-			fi
-		fi
-	}
-	theFirst="${argv[0]}"
-	_chain_bak "${argv[@]}"
-	local res=$?
-	if [ "$res" = 0 -a -n "$cyclicPreserved" ];then
-		_mv_it "$cyclicPreserved" "${argv[0]}"
 	else
-		return $res
+		if [ -z "$reverse" ];then
+			_chain_bak - "${argv[0]}"
+		else
+			_chain_bak_reverse - "${argv[0]}"
+		fi
 	fi
 }
 
@@ -310,11 +493,11 @@ function local_fun(){
 	shift
 	if [ -z "${LOCAL_FUNC_EACH[$fName]}" ] ;then
 		LOCAL_FUNC_EACH[$fName]=1
-		eval "function $fName(){
+		eval 'function '$fName'(){
 			$(while read -j ln;do
 				echo -E $ln
 			done)
-		}"
+		}'
 	fi
 }
 
@@ -546,14 +729,20 @@ function capitalize(){
 	echo -n $F $@
 }
 
+function errmsg_n(){
+	echo -en $error"$@"$plain >&2
+}
+
+
 function errmsg(){
-	if [ -z "$ERRMSG" ]; then
-		ERRMSG="$error$@$plain
-"
+	errmsg_n "$@"
+	if [ -n "$ERRMSG" ];then
+		ERRMSG="$ERRMSG"'
+'"$@"
 	else
-		ERRMSG="$ERRMSG
-$error$@$plain"
+		ERRMSG="$@"
 	fi
+	echo -ne "\n" >&2
 }
 
 
@@ -565,7 +754,8 @@ function info_n(){
 	echo -ne $info$@$plain >&2
 }
 function info(){
-	info_n $@"\n"
+	info_n $@
+	echo -ne "\n" >&2
 }
 
 
@@ -573,12 +763,15 @@ function warning_n(){
 	echo -ne "$warning""$@"  >&2
 }
 function warning(){
-	warning_n "$@""\n"
+	warning_n "$@"
+	echo -ne "\n" >&2
 }
 
 function warn(){
-	warning_n "$@""\n"
+	warning_n "$@"
+	echo -ne "\n" >&2
 }
+
 alias warn_n=warning_n
 
 
@@ -620,11 +813,8 @@ done
 
 
 function exit_if_err(){
-	if [ -n "$1" ]; then
-		errmsg $@
-	fi
+	errmsg "$@"
 	if [ -n "$ERRMSG" ];then
-		echo -en $ERRMSG >&2
 		exit 1
 	fi
 }
@@ -632,9 +822,6 @@ function exit_if_err(){
 function die(){
 	if [ -n "$1" ]; then
 		errmsg $@
-	fi
-	if [ -n "$ERRMSG" ];then
-		echo -en $ERRMSG >&2
 	fi
 	exit 1
 }
