2.73.287

diff --git a/build_burmillaos b/build_burmillaos
--- a/build_burmillaos
+++ b/build_burmillaos
@@ -26,10 +26,13 @@ fi
 
 
 if [ -n "$1" ];then
-	if ! wget https://github.com/burmilla/os/archive/refs/tags/$1.tar.gz --no-clobber -O /tmp/$1.tar.gz; then
-		die "cannot download $1.tar.gz"
-	fi
 	if [ ! -e /tmp/$1.tar.gz ];then
+		if ! wget https://github.com/burmilla/os/archive/refs/tags/$1.tar.gz --no-clobber -O /tmp/$1.tar.gz; then
+			echo "cannot download $1.tar.gz" >&2
+			exit 1
+		fi
+	fi
+	if [ ! -e "/tmp/$1.tar.gz" ];then
 		die "cannot download $1.tar.gz"
 	fi
 	pushd ~/
