2.73.157

diff --git a/chain_bak b/chain_bak
--- a/chain_bak
+++ b/chain_bak
@@ -248,13 +248,13 @@ chain_bak(){
 		local num="$1"
 		local f0="$(_chain_bak_set_file $num)"
 		local f1="$(_chain_bak_set_file $((num + 1)))"
-		dbv rm $f0 $f1
+		dbv rm -rf $f0 $f1
 		if [ -e "$f1" ];then
 			if ! _chain_rm $((num + 1)); then
 				return 1
 			fi
 		fi
-		if ! rm -f $verbose "$f0"; then
+		if ! rm -rf $verbose "$f0"; then
 			return 1
 		fi
 		dbv erased "$f0"
@@ -423,4 +423,157 @@ chain_bak(){
 }
 
 
+_d_id(){
+	echo `stat -c "%d-%i" -L "$1"`
+}
+
+do_recursive_files(){
+	declare -A dstack
+	local dst="$3"
+	local src="$2"
+	local src_dn="${src##*/}"
+	if [ -d "$dst" ];then
+		while [ -z "$src_dn" -a "${src: -1:1}" = "/" ];do
+			src="${src%?}"
+			src_dn="${src##*/}"
+		done
+		if [ -n "$src" ]; then
+			if [ "$src" != "/" -a "$src_dn" != "." -a "$src_dn" != ".." ];then
+				dst="$dst/$src_dn"
+			fi
+		else
+			$src="/"
+		fi
+	fi
+	if [ -d "$src" ];then
+		_do_recursive_files_dir "$1" "$src" "$dst"
+	else
+		"$1" "$2" "$dst"
+	fi
+}
+
+
+_do_recursive_files_dir(){
+	local did=`_d_id "$2"`
+	if [ -n "${dstack[$did]}" -o -z "$did" ];then
+		return
+	fi
+	"$1" "$2" "$3" # check only dir, but not check files in dir
+	local f
+	local dirs
+	local d
+	local IFS=
+	for f in "$2"/*; do
+		if [ -d "$f" ];then
+			dirs+=("$f")
+		else
+			"$1" "$f" "${3%/*}/${f##*/}"
+		fi
+	done
+	dstack[$did]=1
+	for d in "${dirs[@]}"; do
+		_do_recursive_files_dir "$d" "${3%/*}/${d##*/}"
+	done
+	dstack[$did]=
+}
+
+
+_same_content_(){
+	if [ -f "$1" -a -f "$2" ];then
+		if [ -n "$compare" ];then
+			diff "$1" "$2" > /dev/null
+			return $?
+		else
+			return 1
+		fi
+	fi
+	local sts=$(stat -c "%F:%T:%t" "$1")
+	local std=$(stat -c "%F:%T:%t" "$2")
+	if [ "$sts" != "$std" ];then
+		return 1
+	else
+		return 0
+	fi
+}
+
+
+_cp_bak(){
+	if [ -d "$1" ];then
+		if [ -d "$2" ];then
+			return
+		fi
+		if [ -e "$2" -o -L "$2" ];then # file exists or symlink but destination is missing
+			chain_bak ${opts[@]} "$2"
+		fi
+		mkdir "$2"
+		local src="`readlink -f "$1"`"
+		local ug=$(stat -c '%U:%G' "$src")
+		local ac=$(stat -c '%a' "$src")
+		chown $ug "$2"
+		chmod $ac "$2"
+		touch -r "$src" "$2"
+	else
+		dbv $@
+		if [ -e "$2" ]; then
+			if _same_content_ "$1" "$2";then
+				return
+			else
+				chain_bak ${opts[@]} "$2"
+			fi
+		elif [ -L "$2" ]; then # symlink but destination is missing
+			chain_bak ${opts[@]} "$2"
+		fi
+		if [ -e "$1" ]; then
+			dbv $1 "`readlink -f "$1"`"
+			if ! cp -av "`readlink -f "$1"`" "$2"; then
+				:
+			fi
+			dbv
+		elif [ -L "$1" ]; then
+			dbv
+			if ! cp -av "$1" "$2"; then
+				:
+			fi
+			dbv
+		else
+			warn "'$1' is missing"
+		fi
+	fi
+}
+
+
+cp_bak(){
+	local opts
+	local ag
+	local ags
+	local compare
+	local srcs=("${@:1:$(($#-1))}")
+	local dst=${!#}
+	local i=0
+	for ag in "$@"; do
+		if [ "${ag:0:1}" = "-" ];then
+			if [ "$ag" == "--compare" ];then
+				compare=1
+			else
+				opts+=("$ag")
+			fi
+		else
+			ags+=("$ag")
+		fi
+	done
+	if [ ${#ags[@]} -lt 2 ];then
+		die "missing SOURCE and/or DESTINATION argument(s)"
+	fi
+	dst=${ags[-1]}
+	srcs=("${ags[@]:0:${#ags[@]}-1}")
+	if [ -d "$dst" ];then
+		for src in "${srcs[@]}"; do
+			do_recursive_files _cp_bak $src $dst
+		done
+	elif [ ${#ags[@]} -gt 2 ];then
+		die "last argument is not a directory"
+	else
+		do_recursive_files _cp_bak $src $dst
+	fi
+}
 
diff --git a/create_initrd_mod b/create_initrd_mod
--- a/create_initrd_mod
+++ b/create_initrd_mod
@@ -4,6 +4,17 @@
 function create_initrd_mod(){
 	apt-get -y update
 	apt-get -y install cpio btrfs-progs strace nginx git binutils
+	if [ ! -x /usr/bin/yq ]; then
+		if [ -n "`uname -a|grep armv7`" ]; then
+			sudo wget "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm" -q -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
+		fi
+		if [ -n "`uname -a|grep aarc64`" ]; then
+			sudo wget "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm64" -q -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
+		fi
+		if [ -n "`uname -a|grep x86_64`" ]; then
+			sudo wget "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64" -q -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
+		fi
+	fi
 
 	local tmpd=`pwd`
 	local PATH="$tmpd:$PATH"
@@ -18,10 +29,15 @@ function create_initrd_mod(){
 	require do_install
 	require chain_bak
 	require do_mount
+	require vercmp
 
 	if [ ! -x /usr/bin/system-docker ];then
 		die "/usr/bin/system-docker not found"
 	fi
+	if [ ! -x /usr/bin/docker ];then
+		die "/usr/bin/docker not found"
+	fi
+
 	if [ "`id -u`" != 0 ];then
 		die "not super user"
 	fi
@@ -106,6 +122,17 @@ function create_initrd_mod(){
 		ls -la ./usr/bin/ros*
 	else
 		zcat $EXTD/boot_dev/$INITRD_FILE | cpio -idm
+	fi
+
+	DOCKER_IMAGE=`yq ".rancher.services.docker.image" usr/share/ros/os-config.yml`
+	if [ -z "$DOCKER_IMAGE" ];then
+		die cannot find .rancher.services.docker.image in usr/share/ros/os-config.yml
+	fi
+	if ! docker pull $DOCKER_IMAGE; then
+		die cannot pull $DOCKER_IMAGE
+	fi
+	if ! docker save $DOCKER_IMAGE | gzip > usr/share/ros/os-docker-${DOCKER_IMAGE#*:}.tar.gz; then
+		die cannot extract usr/share/ros/os-docker-${DOCKER_IMAGE#*:}.tar.gz
 	fi
 
 	local d
@@ -412,6 +439,7 @@ $libs"
 		nginx
 		strings
 		cp
+		yq
 	END
 	mkdir -p ./idev # for logger
 	mknod ./idev/null c 1 3
@@ -451,6 +479,7 @@ $libs"
 					after_save_cmd_line                \
 					args						\
 					parse_func				\
+					vercmp					\
 					before_sysinit; do
 				dbv $f $d
 				do_install $f $d
