2.46

diff --git a/create_raid1_sibling b/create_raid1_sibling
--- a/create_raid1_sibling
+++ b/create_raid1_sibling
@@ -1,17 +1,45 @@
 #!/bin/bash
 
-if ! ssh $1
-	err "cannot login by ssh on #{$1}"
+#if ! autoload err; then
+#	if ! sudo cp ./err /usr/local/share/zsh/site-functions; then
+#		echo "ERROR: Cannot find module, 'err'"
+#		exit 1
+#	else
+#		if ! autoload err; then
+#			echo "ERROR: Cannot find module, 'err'"
+#			exit 1
+#		fi
+#	fi
+#fi
+#
+#
+#cat /usr/local/share/zsh/site-functions |ssh "$1" /bin/bash <<END
+#	if [ ! -e /usr/local/share/zsh/site-functions ]; then
+#		sudo cat - > /usr/local/share/zsh/site-functions
+#	else
+#		sudo cat - > /dev/null
+#	fi
+#END
+#if [ "$?" != "0" ];then
+#	die "cannot login by ssh on #{$1}"
+#fi
+
+
+SCRIPT_PATH=$(dirname "$(realpath -s "$0")")
+. $SCRIPT_PATH/err
+
+if [ "$#" != 2 ]; then
+	info "Usage: $0 SERVER_NAME DISK_DEVICE(ex. /dev/sda)"
+	die "Too less or too much arguments."
 fi
 
 
-
-cat - > /tmp/create_raid1_sibling.firstS <<'SCRIPT_END'
-
-if [ "`id | awk '{print $1}'`" != "uid=0(root)" ];then
-	sudo $0 $@
-	exit $?
+if ! test_ssh $1
+	die "cannot connect to $1."
 fi
+
+
+ssh_sudo <<'SCRIPT_END'
 
 if [ ! -x "`which gdisk`" ]; then
 	apt-get install -y gdisk
@@ -25,22 +53,19 @@ fi
 
 
 
-if [ "$1" = "" ];then
-	echo "Error: Argument missing."
-	exit 1
+if [ "$A1" = "" ];then
+	die "Argument missing."
 fi
 
 
-if [ "${1:0:7}" != "/dev/sd" -o "${1:8}" != "" ];then
-	echo "cannot use device, $1."
-	exit 1
+if [ "${A1:0:7}" != "/dev/sd" -o "${1:8}" != "" ];then
+	die "cannot use device, $1."
 fi
-if [ ! -e "$1" ];then
-	echo "$1 is not existing."
-	exit 1
+if [ ! -e "$A1" ];then
+	echo "$A1 is not existing."
 fi
 
-TARGET_DISK=$1
+TARGET_DISK=$A1
 BOOT_DEV_NAME=$(readlink -f /dev/disk/by-uuid/`cat /proc/cmdline|egrep -o "efi=UUID=[0-9a-fA-F-]+"|egrep -o "[0-9a-fA-F-]+$"`|awk 'match($1,/[0-9]+$/){print substr($1,0,length($1)-RLENGTH);}'|awk 'match($1,/^\/dev\//){print substr($1,6,length($1)-5);}') # should be OEM disk  (symlinked)
 
 BOOT_DISK=/dev/$BOOT_DEV_NAME
@@ -121,7 +146,12 @@ fi
 dd if=/dev/zero of="$TARGET_DISK"4 bs=100M count=1
 dd if=/dev/zero of="$TARGET_DISK"5 bs=100M count=1
 dd if=/dev/zero of="$TARGET_DISK"7 bs=100M count=1
-partprobe
+
+SCRIPT_END
+
+ssh_reboot
+
+ssh_do <<'SCRIPT_END'
 
 # copy boot partition to new disk (optional)
 # mkdir -p /tmp/{src,dst}
@@ -187,12 +217,6 @@ bstart "$TARGET_DISK"7 /oem_top_lvl
 
 
 SCRIPT_END
-chmod +x /tmp/create_raid1_sibling.first
-scp /tmp/create_raid1_sibling.first $1:
-ssh $1 ./create_raid1_sibling.first $2
-sleep 10
-chmod +x /tmp/create_raid1_sibling.second
-scp /tmp/create_raid1_sibling.second $1:
-ssh $1 ./create_raid1_sibling.second $2
+
 
 
diff --git a/err b/err
--- a/err
+++ b/err
@@ -108,14 +108,110 @@ function die(){
 	if [ -n "$ERRMSG" ];then
 		echo -en $ERRMSG
 	fi
-	UMT=`ssh_inst sudo bash -c mount|grep /installing|awk '{print $3}'`
-	echo unmounting "$UMT"
-	if [ -n "$UMT" ];then
-		ssh_inst sudo umount $UMT
-	fi
-	ssh_inst sudo rmdir /installing/*
-	ssh_inst sudo rmdir /installing
 	exit 1
 }
+
+
+function test_ssh(){
+	if [ $# = "0" ];then
+		die "ssh server argument missing."
+	fi
+	ssh -v -o "ConnectTimeout=5" $1 echo -n > /tmp/test_ssh 2>&1 
+	if [ "$?" = "0" ];then
+		SSH_HOST=$1
+		SSH_PORT=`egrep -o 'debug1: Connecting to .* port [0-9]+' /tmp/test_ssh| egrep -o '[0-9]+$'`
+		if [ -n "$SSH_PORT" ];then
+			return 0
+		fi
+	fi
+	return 1
+}
+
+
+function wait_sshd_start(){
+	if [ -z "$SSH_PORT" -o -z "$SSH_HOST" ];then
+		die "missing ssh paramters. Please execute 'test_ssh' first."
+	fi
+	local SSH_CON_
+	info_n connecting SSH...
+	for i in $(seq 1 120); do
+		sleep 1
+		blue_n "."
+		SSH_CON_=`echo | nc $SSH_HOST $SSH_PORT 2>&1`
+		if [ "${SSH_CON_:0:3}" = "SSH" ];then
+			cyanBgBlue connected
+			return
+		fi
+	done
+	echo
+	die Tried 120 times. Still cannot connect SSH port "($SSH_PORT)". Exited.
+}
+
+
+THIS_FILE="$(realpath -s "$0")"
+
+
+function transfer_arguments(){
+	local i
+	local j=-1
+	while IFS= read -r -d $'\0' i; do
+	    if [ $j != "-1" ];then
+	    	TRANSFER_ARGUMENTS="$TRANSFER_ARGUMENTS$1$j='$i'"$'\n'
+	    fi
+	    j=$(( j + 1 ))
+	done < <(cat /proc/$$/cmdline)
+}
+
+transfer_arguments A
+
+
+function ssh_do(){
+	local sudoing
+	if [ "$1" = "sudo" ];then
+		sudoing=sudo
+		shift
+	fi
+	if [ -z "$SSH_PORT" -o -z "$SSH_HOST" ];then
+		die "missing ssh paramters. Please execute 'test_ssh' first."
+	fi
+	if [ "$#" = "0" ];then
+		RD=`rand 100000000`
+		(echo "set|awk '!/^(BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID)=/ {print \$0}' > /tmp/err.$RD";echo "$TRANSFER_ARGUMENTS";set|awk '!/^(BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID)=/ {print $0}' ;echo "source /tmp/err.$RD;rm /tmp/err.$RD";cat -; echo; echo "exit 0") | ssh -x $SSH_HOST $sudoing bash
+		if [ "$?" = "1" ];then
+			exit 1
+		fi
+	else
+		ssh $SSH_HOST $sudoing $@
+	fi
+}
+
+function ssh_sudo(){
+	ssh_do sudo $@
+}
+
+
+
+
+function ssh_reboot(){
+	ssh_do <<'END'
+		local efi_dev=$(readlink -f /dev/disk/by-uuid/`cat /proc/cmdline|egrep -o "efi=UUID=[0-9a-fA-F-]+"|egrep -o "[0-9a-fA-F-]+$"`|awk 'match($1,/[0-9]+$/){print substr($1,0,length($1)-RLENGTH);}'|awk 'match($1,/^\/dev\//){print substr($1,6,length($1)-5);}')2
+		if [ -z "$efi_dev" ]; then die "boot efi device not found."; fi
+		sudo mkdir -p /tmp/efi_dev
+		sudo mount $efi_dev /tmp/efi_dev
+		sudo touch $efi_dev /tmp/efi_dev/.reboot
+		sudo reboot
+END
+	wait_sshd_start
+	ssh_do <<'END'
+		local efi_dev=$(readlink -f /dev/disk/by-uuid/`cat /proc/cmdline|egrep -o "efi=UUID=[0-9a-fA-F-]+"|egrep -o "[0-9a-fA-F-]+$"`|awk 'match($1,/[0-9]+$/){print substr($1,0,length($1)-RLENGTH);}'|awk 'match($1,/^\/dev\//){print substr($1,6,length($1)-5);}')2
+		if [ -z "$efi_dev" ]; then die "boot efi device not found."; fi
+		sudo mkdir -p /tmp/efi_dev
+		sudo mount $efi_dev /tmp/efi_dev
+		sudo rm /tmp/efi_dev/.reboot
+		sudo umount /tmp/efi_dev
+		sudo rmdir /tmp/efi_dev
+END
+}
+
 
 
