2.9

diff --git a/create_burmillaos_efi_iso b/create_burmillaos_efi_iso
--- a/create_burmillaos_efi_iso
+++ b/create_burmillaos_efi_iso
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+UB_CERT_URL=https://letsencrypt.org/certs/lets-encrypt-r3.pem
+BM_RELEASE_URL=https://github.com/burmilla/os/releases
+UB_RELEASE_URL=https://releases.ubuntu.com
+
 function check_cmd {
 	while (( "$#" )); do
 		if [ -z "`sudo which $1 2>/dev/null`" ];then
@@ -36,7 +40,7 @@ function ver {
 	echo -n ${tmp%%-*}
 }
 
-VERSIONS=`wget https://github.com/burmilla/os/releases --quiet -O - |egrep -o 'expanded_assets/v[0-9].*"'|awk '{sub(/.$/, "", $0);print substr($0,17)}'`
+VERSIONS=`wget $BM_RELEASE_URL --quiet -O - |egrep -o 'expanded_assets/v[0-9].*"'|awk '{sub(/.$/, "", $0);print substr($0,17)}'`
 VERSIONS=`ls $T/ | grep -v efi | grep iso | grep burmillaos | sed -s 's/burmillaos-//;s/.iso//'`"
 "$VERSIONS
 echo "$VERSIONS" > /tmp/$0.ver
@@ -90,56 +94,84 @@ if [ -z "$BURMILLAOS_VER" ];then
 	exit 1
 fi
 
-UB_CERT_URL=https://letsencrypt.org/certs/lets-encrypt-r3.pem
 UB_CERT=$T/${UB_CERT_URL##*/}
 
 
 function WG(){
-	if ! wget $@; then
-		echo "ERROR: wget $@ failed exitting."
-		exit 1
+	local outOpt, outFile, outOpt2
+	for ag in $@;do
+		if [ -n "$outOpt" ];then
+			outFile=$ag
+			break
+		fi
+		if [ "$ag" = "-O" ]; then
+			outOpt=1
+		fi
+	done
+	if [ -z "$outFile" ];then
+		for ag in $@;do
+			if [ -n "`echo $ag|grep -o '^(http|https|ftp)://'`" ];
+				outFile=${ag##*/}
+				outOpt2="-O $outFile"
+				break;
+			fi
+		done
+	fi
+	local nc, go
+	case "$outFile" in
+		"-")
+			go=1
+			;;
+		"")
+			echo "Error: argument error for wget $@. Exiting"
+			exit 1
+			;;
+		*)
+			if [ ! -s "$outFile" ];
+				go=1
+			fi
+			nc=-nc
+	esac
+	
+	if [ -n "$go" ]; then
+		if ! wget $outOpt2 $nc -q $@
+			echo "ERROR: wget $@ failed. Exiting."
+			exit 1
+		fi
+		if [ "$outFie" != "-" ]; then
+			if [ ! -s "$outFie" ]; then
+				echo "ERROR: wget $@ failed. Exiting."
+				exit 1
+			fi
+		fi
 	fi
 }
 
 
 if [ ! -s $UB_CERT ]; then
-	WG --no-check-certificate $UB_CERT_URL -q -nc -O $UB_CERT
-	WG --ca-certificate=$UB_CERT $UB_CERT_URL -q -nc -O $UB_CERT
+	rm -f $UB_CERT.no_check $UB_CERT $UB_CERT.rechecked
+	WG --no-check-certificate $UB_CERT_URL -O $UB_CERT.no_check
+	WG --ca-certificate=$UB_CERT.no_check $UB_CERT_URL -O $UB_CERT
+	WG --ca-certificate=$UB_CERT $UB_CERT_URL -O $UB_CERT.rechecked
+	if ! diff $UB_CERT.rechecked $UB_CERT; then
+		echo "ERROR: Abnormal certificate provided from $UB_CERT_URL. Exitting"
+		exit 1
+	fi
+	rm -f $UB_CERT.no_check $UB_CERT.rechecked
 fi
 
 BURMILLAOS_VER=${BURMILLAOS_VER%$'\n'*}
 echo BurmillaOS Version: $BURMILLAOS_VER
 BURMILLA_ISO="$T"/burmillaos-$BURMILLAOS_VER.iso
 
-LATEST_U=`wget --ca-certificate=$UB_CERT -O - https://releases.ubuntu.com/ 2>/dev/null|awk '/Ubuntu [0-9]+(\.[0-9]+)+ LTS/{print $0}'|head -1|awk '{match($0, /Ubuntu [0-9]+(\.[0-9]+)+ LTS \([^)]+\)/); print substr($0, RSTART, RLENGTH)}'`
+LATEST_U=`WG --ca-certificate=$UB_CERT -O - $UB_RELEASE_URL/ 2>/dev/null|awk '/Ubuntu [0-9]+(\.[0-9]+)+ LTS/{print $0}'|head -1|awk '{match($0, /Ubuntu [0-9]+(\.[0-9]+)+ LTS \([^)]+\)/); print substr($0, RSTART, RLENGTH)}'`
 LATEST_UV=`echo $LATEST_U | awk '{print $2}'`
-UDIR=`wget --ca-certificate=$UB_CERT -O - https://releases.ubuntu.com/ 2>/dev/null|grep "$LATEST_U"|grep href| head -1|awk '{match($0,/href="[^"]+"/);print substr($0,RSTART+6,RLENGTH-7)}'`
+UDIR=`WG --ca-certificate=$UB_CERT -O - $UB_RELEASE_URL/ 2>/dev/null|grep "$LATEST_U"|grep href| head -1|awk '{match($0,/href="[^"]+"/);print substr($0,RSTART+6,RLENGTH-7)}'`
 UBUNTU_ISO="$T"/ubuntu-$LATEST_UV-live-server-amd64.iso
 echo Ubuntu Version: $LATEST_UV
 
-if [ ! -s $BURMILLA_ISO ];then
-	if ! wget -nc https://github.com/burmilla/os/releases/download/$BURMILLAOS_VER/burmillaos-$BURMILLAOS_VER.iso -O $BURMILLA_ISO; then
-		echo "Error: cannot download burmilla iso. exitting"
-		exit 1
-	else
-		if [ ! -s $BURMILLA_ISO ];then
-			echo "Error: cannot download burmilla iso. exitting"
-			exit 1
-		fi
-	fi
-fi
-
-if [ ! -s $UBUNTU_ISO ];then
-	if ! wget -nc --ca-certificate=$UB_CERT https://releases.ubuntu.com/$UDIR"ubuntu-$LATEST_UV-live-server-amd64.iso" -O $UBUNTU_ISO; then
-		echo "Error: cannot download ubuntu iso. exitting"
-		exit 1
-	else
-		if [ ! -s $UBUNTU_ISO ];then
-			echo "Error: cannot download burmilla iso. exitting"
-			exit 1
-		fi
-	fi
-fi
+WG $BM_RELEASE_URL/download/$BURMILLAOS_VER/burmillaos-$BURMILLAOS_VER.iso -O $BURMILLA_ISO
+WG --ca-certificate=$UB_CERT $UB_RELEASE_URL/$UDIR"ubuntu-$LATEST_UV-live-server-amd64.iso" -O $UBUNTU_ISO
 
 
 UD="$T"/tmpubuntu
