2.65.1

diff --git a/do_install b/do_install
--- a/do_install
+++ b/do_install
@@ -8,74 +8,71 @@ function do_install(){
 	local d
 	shift
 	local newLns
+	local sudo
+	if [ "`id -u`" != 0 ];then
+		sudo=sudo
+	fi
 	function _do_install_each(){
 		local d="$1"
 		if [ ! -d "$d" ];then
 			if [ -e "$d" ];then
 				die "'$d' is not a directory."
 			else
-				if ! mkdir -p "$d";then
+				if ! $sudo mkdir -p "$d";then
 					die "cannot create directory, '$d'"
 				fi
 			fi
 		fi
 		#echo "[ ! -e $d/$SUPPORT_LIB_NAME -o `stat $d/$SUPPORT_LIB_NAME -c %Y` -lt $SUPPORT_LIB_MTIME ]"
 		local do
-		if [ ! -e $d/$SUPPORT_LIB_NAME ]; then
+		local sLib=$d/usr/share/$SUPPORT_LIB_NAME/$SUPPORT_LIB_NAME
+		if [ ! -e $sLib ]; then
 			do=1
 		else
-			if [ "`stat $d/$SUPPORT_LIB_NAME -c %Y`" -lt $SUPPORT_LIB_MTIME ];then
+			if [ "`stat $sLib -c %Y`" -lt $SUPPORT_LIB_MTIME ];then
 				do=1
 			fi
 		fi
 		if [ -n "$do" ];then
-			echo -E "$SUPPORT_LIB_CONTENT" > $d/$SUPPORT_LIB_NAME
-			chmod +x $d/$SUPPORT_LIB_NAME
-		fi
-		if [ -z "$newLns" ];then
-			(
-				trim_indent <<END
-					#!/bin/bash
-					source $SUPPORT_LIB_NAME
-END
-				if ! declare -f $to_inst ;then
-					die "function, '$to_inst' does not exist"
-				fi
-				trim_indent <<'END'
-					eval '
-						THIS_FILE'$SCRIPT_ID'=$(__FILE__)
-						THE_CMD'$SCRIPT_ID'=$(readlink -f $0)
-						if [ "${THE_CMD'$SCRIPT_ID'}" = "${THIS_FILE'$SCRIPT_ID'}" ];then
-							unset THIS_FILE'$SCRIPT_ID'
-							unset THE_CMD'$SCRIPT_ID'
-END
-				echo "
-							'$to_inst' \$@
-						fi
-					'
-"
-			) > $SCRIPT_TMP_DIR/$to_inst
-			newLns="`cat $SCRIPT_TMP_DIR/$to_inst`"
-		fi
-		if [ ! -e "$d/$to_inst" ];then
-			do=1
-		else
-			if [ "$newLns" != "`cat $d/$to_inst`" ]; then
-				do=1
+			if ! $sudo mkdir -p $d/usr/share/$SUPPORT_LIB_NAME;then
+				die "cannot create directory, $d/usr/share/$SUPPORT_LIB_NAME"
 			fi
+			echo -E "$SUPPORT_LIB_CONTENT" | $sudo tee $sLib > /dev/null
+			if [ "$?" != 0 ];then
+				die "cannot create file, $sLib"
+			fi
+			$sudo chmod +x $sLib
+			$sudo ln -sf ../../$sLib $d/usr/bin/$SUPPORT_LIB_NAME
 		fi
-		if [ -n "$do" ];then
-			if [ ! -e $d/$to_inst ];then
-				if [ ! -w $d ];then
-					die "cannot write to '$d/$to_inst'"
+		local from
+		if [ ! -e "./$to_inst" ];then
+			if [ ! -e "`__FILE_DIR__`/$to_inst" ];then
+				if [ ! -e "/usr/share/$SUPPORT_LIB_NAME/$to_inst" ];then
+					die "'$to_inst' is found neither in current directory nor in directory, '/usr/share/$SUPPORT_LIB_NAME', nor in directory, '`__FILE_DIR__`'"
+				else
+					from="/usr/share/$SUPPORT_LIB_NAME/$to_inst"
 				fi
 			else
-				if [ ! -w $d/$to_inst ];then
-					die "cannot write to '$d/$to_inst'"
-				fi
+				from="`__FILE_DIR__`/$to_inst"
 			fi
-			echo -E "$newLns" > $d/$to_inst
-			chmod +x $d/$to_inst
+		else
+			from="./$to_inst"
+		fi
+		local sCmd="$d/usr/share/$SUPPORT_LIB_NAME/$to_inst"
+		do=
+		if [ ! -e "$sCmd" ];then
+			do=1
+		else
+			if [ "`readlink -f "$from"`" = "`readlink -f "$sCmd"`" ];then
+				die "'$from' and '$sCmd' is a same file."
+			fi
+			if [ "`stat "$from" -c %Y`" -lt "`stat "$sCmd" -c %Y`" ];then
+				do=1
+			fi
+		fi
+		if [ -n "$do" ];then
+			$sudo cp -av "$from" "$sCmd"
+			$sudo ln -sf "../../usr/share/$SUPPORT_LIB_NAME/$SUPPORT_LIB_NAME" "$d/usr/bin/$to_inst"
 		fi
 	}
 	if [ ${#@} = 0 ];then
