2.73.238

diff --git a/do_mount b/do_mount
--- a/do_mount
+++ b/do_mount
@@ -136,7 +136,6 @@ function do_mount(){
 	moptsNoDeg=$(joinopt "-o " , "${!moptsNoDeg[@]}")
 	moptsWithDeg=$(joinopt "-o " , "${!moptsWithDeg[@]}")
 	declare -A to_mount_cand
-	local to_mount
 	local srcs
 	if [[ $src =~ ^[0-9]*$ ]];then
 		require partNum2Dev
@@ -188,7 +187,7 @@ function do_mount(){
 		fi
 		local type=`/sbin/blkid $src|sed -r 's/.*TYPE="([^"]+)".*/\1/g'`
 		if [ -z "$type" ];then
-			_err "cannot detect filesystem of '$to_mount'."
+			_err "cannot detect filesystem of '$src'."
 			continue
 		fi
 		local hasErr
@@ -202,7 +201,7 @@ function do_mount(){
 				_err "cannot use option for swap partition"
 			fi
 			if [ -z "$hasErr" ];then
-				swapon $to_mount
+				swapon $src
 				return $?
 			fi
 		else
@@ -230,10 +229,10 @@ function do_mount(){
 					fi
 				fi
 
-				local devices=("`blkid2 --get-siblings $to_mount`")
+				local devices=("`blkid2 --get-siblings $src`")
 				if [ "$?" != 0 -o "${#devices[@]}" = 0 ];then
 					dbv "${#devices[@]}"
-					_die "'blkid2 --get-siblings $to_mount' failed"
+					_die "'blkid2 --get-siblings $src' failed"
 				fi
 				dbv $devices
 				local dev
@@ -257,7 +256,7 @@ function do_mount(){
 				fi
 				if [ -z "$forceDegraded" ];then
 					local i=0
-					while ! _mount $opts $moptsNoDeg $to_mount $dst;do
+					while ! _mount $opts $moptsNoDeg $src $dst;do
 						if [ $i = 0 ];then
 							info_n retrying .
 						else
@@ -266,7 +265,7 @@ function do_mount(){
 						i=$((i + 1))
 						if [ $i = 5 ];then
 							echo
-							_mount $opts $moptsWithDeg $to_mount $dst
+							_mount $opts $moptsWithDeg $src $dst
 							res=$?
 							if [ "$res" = 0 ];then
 								_warn "Mounted degraded drive."
@@ -277,15 +276,15 @@ function do_mount(){
 					done
 					res=$?
 				else
-					_mount $opts $moptsWithDeg $to_mount $dst
+					_mount $opts $moptsWithDeg $src $dst
 					res=$?
 				fi
 			else
-				_mount $opts $mopts $to_mount $dst
+				_mount $opts $mopts $src $dst
 				res=$?
 			fi
 			if [ "$res" != "0" ];then
-				err "cannot mount $to_mount on $dst"
+				err "cannot mount $src on $dst"
 			else
 				return $res
 			fi
