3.2.56

diff --git a/install_burmillaos_on_btrfs b/install_burmillaos_on_btrfs
--- a/install_burmillaos_on_btrfs
+++ b/install_burmillaos_on_btrfs
@@ -1031,10 +1031,10 @@ sleep 5
 ssh_sudo <<'FINAL'
 	dbv ${!SCRIPT_FILES[@]}
 
-	apt_check gdisk lvm2 dosfstools btrfs-progs parted util-linux cpio gzip fdisk strace
+	apt_check gdisk lvm2 dosfstools btrfs-progs parted util-linux cpio gzip fdisk strace 2> /dev/null
 	for l in RANCHER_BOOT RANCHER_OEM RANCHER_STATE RANCHER_SWAP; do
-		b2res="`blkid2 LABEL=$l`"
-		if [[ $b2res =~ (^|\ )$TARGET_DEV($|\ )  ]]; then
+		b2res="`blkid2 LABEL=$l > /dev/null`"
+		if ! [[ $b2res =~ (^|\ )$TARGET_DEV($|\ )  ]]; then
 			warn Partition, LABEL=$l, not found.
 			part_not_found=1
 		fi
@@ -1107,10 +1107,10 @@ ssh_sudo <<'FINAL'
 		sleep 1
 		partprobe
 		sleep 1
-		mkswap -L RANCHER_SWAP $TARGET_DEV3 <<END
+		mkswap -L RANCHER_SWAP $TARGET_DEV3 <<"	END"
 		y
 		END
-		mkfs.vfat -F32 -n EFI $TARGET_DEV2 <<END
+		mkfs.vfat -F32 -n EFI $TARGET_DEV2 <<"	END"
 		y
 		END
 	fi
@@ -1123,6 +1123,26 @@ if [ "$__SSH_DO_RET" = 1 ];then
 	yellowBgRed_n  "[y/n]: "
 	if ! ask_yes_no; then
 		die "User terminated. Cannot coninue installation."
+	else
+		ssh_sudo <<FINAL
+	do_mount -v --salvage-btrfs $TARGET_DEV7 /installing/oem_top
+FINAL
+		if [ "$__SSH_DO_RET" = 0 ];then
+			ssh_sudo umount /installing/oem_top
+			whiteBgRed "'$TARGET_DEV7' is degraded but still redable."
+			whiteBgRed_n "Really format it?"
+			yellowBgRed_n  "[y/n]: "
+			if ! ask_yes_no; then
+				die "User terminated. Cannot coninue installation."
+			else
+				whiteBgRed "All data in '$TARGET_DEV7' will be lost."
+				whiteBgRed_n "Really format it?"
+				yellowBgRed_n  "[y/n]: "
+				if ! ask_yes_no; then
+					die "User terminated. Cannot coninue installation."
+				fi
+			fi
+		fi
 	fi
 	ssh_sudo <<'FINAL'
 		mkfs.btrfs -L RANCHER_OEM -f $TARGET_DEV7
